import { LegalPage } from '../legal-page';

export default function DatenschutzPage() {
  return (
    <LegalPage kicker="Rechtliches / 01" title="Datenschutzerklärung" intro="Hier erklären wir, welche Daten beim Besuch dieser Website und bei einer Reservierungsanfrage verarbeitet werden.">
      <section><h2>1. Verantwortlicher</h2><p>Endstation – Alter Bahnhof, Bahnhofsplatz 6, 99974 Mühlhausen. Datenschutzanfragen können telefonisch unter <a href="tel:+4915780791277">+49 1578 0791277</a> gestellt werden.</p></section>
      <section><h2>2. Aufruf der Website</h2><p>Beim Aufruf können technisch notwendige Zugriffsdaten wie IP-Adresse, Zeitpunkt, angeforderte Seite, Browser- und Geräteinformationen durch den Hosting- und Sicherheitsdienst verarbeitet werden. Dazu können automatisierte Schutzmechanismen gegen missbräuchliche Zugriffe gehören. Dies dient der sicheren und stabilen Bereitstellung der Website. Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO.</p></section>
      <section><h2>3. Reservierungsanfragen</h2><p>Das Formular verarbeitet Name, Telefonnummer, Datum, Uhrzeit, Personenzahl und den angegebenen Wunsch ausschließlich im Browser. Die Website speichert diese Angaben nicht in einer eigenen Datenbank. Beim Absenden werden sie in eine WhatsApp-Nachricht übernommen. Rechtsgrundlage für die Bearbeitung der Anfrage ist Art. 6 Abs. 1 lit. b DSGVO.</p></section>
      <section><h2>4. WhatsApp und Google Kalender</h2><p>WhatsApp wird erst nach dem Absenden geöffnet. Dabei werden die eingegebenen Angaben an WhatsApp beziehungsweise Meta übermittelt. Der optionale Google-Kalender-Link wird lokal erzeugt; erst beim Anklicken werden die Termindaten an Google übermittelt. Für die weitere Verarbeitung gelten die Datenschutzbestimmungen der jeweiligen Anbieter.</p><p><a href="https://www.whatsapp.com/legal/privacy-policy-eea" target="_blank" rel="noreferrer">Datenschutz bei WhatsApp ↗</a><br /><a href="https://policies.google.com/privacy" target="_blank" rel="noreferrer">Datenschutz bei Google ↗</a></p></section>
      <section><h2>5. Schutz vor Mehrfachanfragen</h2><p>Zur Abwehr unmittelbar wiederholter Einsendungen wird im Sitzungsspeicher des Browsers ein Zeitstempel mit dem Namen „endstation-last-reservation“ abgelegt. Er enthält keine Formulardaten, wird nur für die einminütige Sperre verwendet und spätestens beim Schließen des Browser-Tabs gelöscht.</p></section>
      <section><h2>6. Speicherdauer</h2><p>Die Website selbst speichert keine Reservierungsdaten. Für Daten, die über WhatsApp übermittelt werden, gilt: Sie werden nur so lange aufbewahrt, wie dies zur Bearbeitung der Anfrage und für gesetzliche Nachweispflichten erforderlich ist. Nicht benötigte Anfragen sollen regelmäßig gelöscht werden.</p></section>
      <section><h2>7. Rechte betroffener Personen</h2><p>Betroffene Personen haben im gesetzlichen Umfang Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit und Widerspruch. Außerdem besteht ein Beschwerderecht bei einer Datenschutzaufsichtsbehörde.</p></section>
      <section><h2>8. Analytics und Drittinhalte</h2><p>Im Seitencode sind derzeit keine Analyse- oder Werbetracker und keine Social-Media-Frames eingebunden. Der Hostingdienst kann ausschließlich für Betrieb und Sicherheit notwendige Schutztechnik ausliefern. Instagram, Google, WhatsApp und Produktquellen werden ansonsten nur als externe Links aufgerufen.</p></section>
    </LegalPage>
  );
}
